AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ApiGatewayTokenAuthorizerEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/handler
      Handler: apiGatewayTokenAuthorizerEvent.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          COGNITO_POOL_ID: ''
          COGNITO_REGION: ''
          COGNITO_CLIENT_ID: ''
          AZURE_TENANT_ID: ''
          AZURE_CLIENT_ID: ''

Outputs:

  AGTokenAuthorizerEventLambdaFunction:
    Description: "API Gateway Authorizor Event Lambda Function ARN"
    Value: !GetAtt ApiGatewayTokenAuthorizerEvent.Arn
